import type { Permission } from "@/lib/permissions";
import { HIGH_RISK_ACTION_KEYS, isHighRiskActionKey } from "@/lib/actions/high-risk";
import {
  customerSearchInput,
  draftFromIdsInput,
  emptyInput,
  identifyFollowupsInput,
  identifyOverdueInput,
  identifyRenewalsInput,
  jobSearchInput,
  proposeAssignmentInput,
  reportInput,
  reviewIdentifyInput,
  sendFromRequestInput,
  socialDraftInput,
  taskPrepareInput,
} from "@/lib/actions/schemas";
import { ACTION_REGISTRY_VERSION, type ActionDefinition } from "@/lib/actions/types";

function define(def: ActionDefinition): ActionDefinition {
  return { ...def, version: def.version || ACTION_REGISTRY_VERSION };
}

const ACTIONS: ActionDefinition[] = [
  define({
    key: "customer.search",
    name: "Search customers",
    description: "Find customers in this company by name, phone, or email.",
    category: "customer",
    level: "READ",
    riskLevel: "LOW",
    requiredPermission: "customers:view",
    requiresApproval: false,
    externalSideEffect: false,
    provider: "contractoryou",
    inputSchema: customerSearchInput,
    version: 1,
  }),
  define({
    key: "job.search",
    name: "Search jobs",
    description: "Find jobs in this company by number, customer, or assignment state.",
    category: "job",
    level: "READ",
    riskLevel: "LOW",
    requiredPermission: "jobs:view",
    requiresApproval: false,
    externalSideEffect: false,
    provider: "contractoryou",
    inputSchema: jobSearchInput,
    version: 1,
  }),
  define({
    key: "estimate.identify_followups",
    name: "Identify estimate follow-ups",
    description: "Find open estimates that meet deterministic follow-up criteria.",
    category: "estimate",
    level: "READ",
    riskLevel: "LOW",
    requiredPermission: "estimates:view",
    requiresApproval: false,
    externalSideEffect: false,
    provider: "contractoryou",
    inputSchema: identifyFollowupsInput,
    version: 1,
  }),
  define({
    key: "invoice.identify_overdue",
    name: "Identify overdue invoices",
    description: "Find unpaid invoices that are past due.",
    category: "invoice",
    level: "READ",
    riskLevel: "LOW",
    requiredPermission: "invoices:view",
    requiresApproval: false,
    externalSideEffect: false,
    provider: "contractoryou",
    inputSchema: identifyOverdueInput,
    version: 1,
  }),
  define({
    key: "membership.identify_renewals",
    name: "Identify membership renewals",
    description: "Find active memberships expiring in the coming days.",
    category: "membership",
    level: "READ",
    riskLevel: "LOW",
    requiredPermission: "memberships:view",
    requiresApproval: false,
    externalSideEffect: false,
    provider: "contractoryou",
    inputSchema: identifyRenewalsInput,
    version: 1,
  }),
  define({
    key: "review.identify_candidates",
    name: "Identify review candidates",
    description: "Find completed, paid jobs that meet review-request eligibility.",
    category: "review",
    level: "READ",
    riskLevel: "LOW",
    requiredPermission: "marketing:view",
    requiresApproval: false,
    externalSideEffect: false,
    provider: "contractoryou",
    inputSchema: reviewIdentifyInput,
    version: 1,
  }),
  define({
    key: "report.sales_summary",
    name: "Sales summary",
    description: "Deterministic sales metrics for this company.",
    category: "report",
    level: "READ",
    riskLevel: "LOW",
    requiredPermission: "reports:view",
    requiresApproval: false,
    externalSideEffect: false,
    provider: "contractoryou",
    inputSchema: reportInput,
    version: 1,
  }),
  define({
    key: "report.money_summary",
    name: "Money summary",
    description: "Deterministic invoice and collection metrics.",
    category: "report",
    level: "READ",
    riskLevel: "LOW",
    requiredPermission: ["invoices:view", "reports:view"],
    requiresApproval: false,
    externalSideEffect: false,
    provider: "contractoryou",
    inputSchema: reportInput,
    version: 1,
  }),
  define({
    key: "report.job_profitability",
    name: "Job profitability",
    description: "Verified job revenue, cost, and profit. Not a guess.",
    category: "report",
    level: "READ",
    riskLevel: "LOW",
    requiredPermission: "job_costs:view",
    requiresApproval: false,
    externalSideEffect: false,
    provider: "contractoryou",
    inputSchema: emptyInput,
    version: 1,
  }),
  define({
    key: "report.team_performance",
    name: "Team performance",
    description: "Verified technician scorecards for the company.",
    category: "report",
    level: "READ",
    riskLevel: "LOW",
    requiredPermission: "performance:view_team",
    requiresApproval: false,
    externalSideEffect: false,
    provider: "contractoryou",
    inputSchema: reportInput,
    version: 1,
  }),
  define({
    key: "communication.draft_sms",
    name: "Draft SMS",
    description: "Prepare SMS drafts from verified records. Nothing is sent.",
    category: "communication",
    level: "PREPARE",
    riskLevel: "MEDIUM",
    requiredPermission: "marketing:manage",
    requiresApproval: true,
    externalSideEffect: false,
    provider: "none",
    inputSchema: draftFromIdsInput,
    version: 1,
  }),
  define({
    key: "estimate.draft_followup",
    name: "Draft estimate follow-ups",
    description: "Prepare personalized estimate follow-up texts. Nothing is sent.",
    category: "estimate",
    level: "PREPARE",
    riskLevel: "MEDIUM",
    requiredPermission: "estimates:view",
    requiresApproval: true,
    externalSideEffect: false,
    provider: "none",
    inputSchema: draftFromIdsInput,
    version: 1,
  }),
  define({
    key: "invoice.draft_payment_reminder",
    name: "Draft payment reminders",
    description: "Prepare overdue invoice reminder texts. Nothing is sent.",
    category: "invoice",
    level: "PREPARE",
    riskLevel: "MEDIUM",
    requiredPermission: "invoices:view",
    requiresApproval: true,
    externalSideEffect: false,
    provider: "none",
    inputSchema: draftFromIdsInput,
    version: 1,
  }),
  define({
    key: "membership.draft_renewal",
    name: "Draft membership renewals",
    description: "Prepare membership renewal texts. Nothing is sent.",
    category: "membership",
    level: "PREPARE",
    riskLevel: "MEDIUM",
    requiredPermission: "memberships:view",
    requiresApproval: true,
    externalSideEffect: false,
    provider: "none",
    inputSchema: draftFromIdsInput,
    version: 1,
  }),
  define({
    key: "review.draft_request",
    name: "Draft review requests",
    description: "Prepare review-request messages. Nothing is sent.",
    category: "review",
    level: "PREPARE",
    riskLevel: "MEDIUM",
    requiredPermission: "marketing:view",
    requiresApproval: true,
    externalSideEffect: false,
    provider: "none",
    inputSchema: draftFromIdsInput,
    version: 1,
  }),
  define({
    key: "social.create_draft",
    name: "Draft social post",
    description: "Create an internal social post draft. Nothing is published.",
    category: "social",
    level: "PREPARE",
    riskLevel: "MEDIUM",
    requiredPermission: "marketing:manage",
    requiresApproval: true,
    externalSideEffect: false,
    provider: "none",
    inputSchema: socialDraftInput,
    version: 1,
  }),
  define({
    key: "job.propose_assignment",
    name: "Propose job assignments",
    description: "Recommend technicians for unassigned jobs. Does not move anyone.",
    category: "dispatch",
    level: "PREPARE",
    riskLevel: "MEDIUM",
    requiredPermission: "schedule:view",
    requiresApproval: true,
    externalSideEffect: false,
    provider: "none",
    inputSchema: proposeAssignmentInput,
    version: 1,
  }),
  define({
    key: "task.prepare_bulk",
    name: "Prepare office tasks",
    description: "Prepare internal tasks. Nothing is created until approval.",
    category: "task",
    level: "PREPARE",
    riskLevel: "LOW",
    requiredPermission: "jobs:manage",
    requiresApproval: true,
    externalSideEffect: false,
    provider: "none",
    inputSchema: taskPrepareInput,
    version: 1,
  }),
  define({
    key: "communication.send_sms",
    name: "Send SMS",
    description: "Send approved SMS through the company communications provider.",
    category: "communication",
    level: "EXECUTE",
    riskLevel: "HIGH",
    requiredPermission: "marketing:manage",
    requiresApproval: true,
    externalSideEffect: true,
    provider: "communication",
    inputSchema: sendFromRequestInput,
    version: 1,
  }),
  define({
    key: "estimate.send_followup",
    name: "Send estimate follow-ups",
    description: "Send approved estimate follow-ups through HighLevel when connected.",
    category: "estimate",
    level: "EXECUTE",
    riskLevel: "HIGH",
    requiredPermission: "marketing:manage",
    requiresApproval: true,
    externalSideEffect: true,
    provider: "communication",
    inputSchema: sendFromRequestInput,
    version: 1,
  }),
  define({
    key: "invoice.send_payment_reminder",
    name: "Send payment reminders",
    description: "Send approved invoice reminders through HighLevel when connected.",
    category: "invoice",
    level: "EXECUTE",
    riskLevel: "HIGH",
    requiredPermission: "marketing:manage",
    requiresApproval: true,
    externalSideEffect: true,
    provider: "communication",
    inputSchema: sendFromRequestInput,
    version: 1,
  }),
  define({
    key: "membership.send_renewal",
    name: "Send membership renewals",
    description: "Send approved membership renewal texts through HighLevel when connected.",
    category: "membership",
    level: "EXECUTE",
    riskLevel: "HIGH",
    requiredPermission: "marketing:manage",
    requiresApproval: true,
    externalSideEffect: true,
    provider: "communication",
    inputSchema: sendFromRequestInput,
    version: 1,
  }),
  define({
    key: "review.send_request",
    name: "Send review requests",
    description: "Send review requests only when HighLevel Reviews is authorized.",
    category: "review",
    level: "EXECUTE",
    riskLevel: "HIGH",
    requiredPermission: "marketing:manage",
    requiresApproval: true,
    externalSideEffect: true,
    provider: "highlevel",
    inputSchema: sendFromRequestInput,
    version: 1,
  }),
  define({
    key: "social.schedule_post",
    name: "Schedule social post",
    description: "Schedule an approved social post through HighLevel Social Planner.",
    category: "social",
    level: "EXECUTE",
    riskLevel: "HIGH",
    requiredPermission: "marketing:manage",
    requiresApproval: true,
    externalSideEffect: true,
    provider: "highlevel",
    inputSchema: sendFromRequestInput,
    version: 1,
  }),
  define({
    key: "task.create",
    name: "Create tasks",
    description: "Create approved internal office tasks.",
    category: "task",
    level: "EXECUTE",
    riskLevel: "LOW",
    requiredPermission: "jobs:manage",
    requiresApproval: true,
    externalSideEffect: false,
    provider: "contractoryou",
    inputSchema: sendFromRequestInput,
    version: 1,
  }),
  define({
    key: "job.assign",
    name: "Assign jobs",
    description: "Assign approved jobs to recommended technicians.",
    category: "dispatch",
    level: "EXECUTE",
    riskLevel: "MEDIUM",
    requiredPermission: "schedule:manage",
    requiresApproval: true,
    externalSideEffect: false,
    provider: "contractoryou",
    inputSchema: sendFromRequestInput,
    version: 1,
  }),
];

const BY_KEY = new Map(ACTIONS.map((action) => [action.key, action]));

export function listRegisteredActions() {
  return ACTIONS.slice();
}

export function getRegisteredAction(key: string) {
  return BY_KEY.get(key) ?? null;
}

export function isRegisteredAction(key: string) {
  return BY_KEY.has(key);
}

export function assertInvocableAction(key: string) {
  if (isHighRiskActionKey(key) || (HIGH_RISK_ACTION_KEYS as readonly string[]).includes(key)) {
    return { ok: false as const, error: "That high-risk action is not available through Ask ContractorYou." };
  }
  const definition = getRegisteredAction(key);
  if (!definition) {
    return { ok: false as const, error: "That action is not registered." };
  }
  return { ok: true as const, definition };
}

export function requiredPermissionsOf(definition: ActionDefinition): Permission[] {
  return Array.isArray(definition.requiredPermission)
    ? definition.requiredPermission
    : [definition.requiredPermission];
}

export function openaiActionToolSpecs() {
  return ACTIONS.filter((action) => action.level !== "EXECUTE").map((action) => ({
    type: "function" as const,
    function: {
      name: action.key.replaceAll(".", "_"),
      description: action.description,
      parameters: {
        type: "object",
        additionalProperties: false,
        properties: {
          recordIds: { type: "array", items: { type: "string" } },
          query: { type: "string" },
          minCents: { type: "number" },
          minDays: { type: "number" },
          withinDays: { type: "number" },
          period: { type: "string" },
          topic: { type: "string" },
        },
      },
    },
  }));
}

export function actionKeyFromToolName(name: string) {
  if (isRegisteredAction(name)) return name;
  const dotted = name.replaceAll("_", ".");
  if (isRegisteredAction(dotted)) return dotted;
  return null;
}

export { HIGH_RISK_ACTION_KEYS };
